config/routes.rb
Rails.application.routes.draw do
  get 'trees/index'
  get 'trees/new'
  get 'trees/show'
  get 'trees/edit'
  get 'printers/index'
  get 'printers/show'
  get 'printers/new'
  get 'cartriges/index'
  get 'cartriges/show'
  get 'cartriges/new'
  get 'main/index'

  resources :cartriges, :printers 

  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartrige.rb
class Cartrige < ApplicationRecord
  @file
  has_many :printers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 , too_short: "Мало символов, минимум 5"}
  validates :description, presence:true, length: { minimum: 5 , too_short: "Мало символов, минимум 5"}
  validates :color, presence: true, length: { minimum: 5 , too_short: "Мало символов, минимум 5"}
  validates :resource, presence: true, numericality: { only_integer: true, greater_than: 999, message: "Должно быть больше 999" }

  def get_printers
  end
end

app/models/printer.rb
class Printer < ApplicationRecord
  @file
belongs_to :cartrige


  validates :title,
   presence: true, length: { minimum: 5 , too_short: "Мало символов, минимум 5"}
  validates :description,
  presence: true, length: { minimum: 5 , too_short: "Мало символов, минимум 5"}
  validates :cartrige_id, presence: true, numericality: { only_integer: true}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cartriges_controller.rb
class CartrigesController < ApplicationController
  def index
    @cartriges = Cartrige.order("id desc").all
  end

  def show
    @cartrige = Cartrige.find(params[:id])
  end

  def new
    @cartrige = Cartrige.new
  end

  def edit
    @cartrige = Cartrige.find(params[:id])
  end

  def create
    cartrige_params[:photo].original_filename = "#{Time.now.to_i}" << cartrige_params[:photo].original_filename

    #File.open(Rails.root.join('app','assets','images',
      #cartrige_params[:photo].original_filename), 'wb') do |f|
        #f.write(cartrige_params[:photo].read)
      #end
    file_upload(cartrige_params[:photo])


    @cartrige = Cartrige.new(
      :title => cartrige_params[:title],
      :description => cartrige_params[:description],
      :color => cartrige_params[:color],
      :resource => cartrige_params[:resource],
      :photo => cartrige_params[:photo].original_filename)
    if @cartrige.save
       redirect_to @cartrige
    else
      render "new"
    end
  end

  def update
    @cartrige = Cartrige.find(params[:id])
    file_remove(@cartrige.photo)
    cartrige_params[:photo].original_filename = "#{Time.now.to_i}" << cartrige_params[:photo].original_filename
    file_upload(cartrige_params[:photo])

    if @cartrige.update(
      :title => cartrige_params[:title],
    :description => cartrige_params[:description],
    :color => cartrige_params[:color],
    :resource => cartrige_params[:resource],
    :photo => cartrige_params[:photo].original_filename)
      redirect_to @cartrige
    else
      render "edit"
    end
  end

  def destroy
    @cartrige = Cartrige.find(params[:id])
    file_remove(@cartrige.photo)

   @cartrige.destroy
   redirect_to cartriges_path
  end

private
  def cartrige_params
    params.require(:cartrige).permit(:title,:description,:color,:resource,:photo)
  end

  def file_remove(file_name)
    File.delete(Rails.root.join('app','assets','images','cartriges',
       file_name)) if File.exist?(Rails.root.join('app','assets','images','cartriges',
          file_name))
  end

  def file_upload(file)
    File.open(Rails.root.join('app','assets','images','cartriges',
       file.original_filename), 'wb') do |f|
       f.write(file.read)
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @lol = 'sdaasd'
  end
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  def index
    @printers = Printer.order("id desc").all
  end

  def show
    @printer = Printer.find(params[:id])
  end

  def new
    @printer = Printer.new
  end

  def edit
    @printer = Printer.find(params[:id])
  end

  def create
    printer_params[:photo].original_filename = "#{Time.now.to_i}" << printer_params[:photo].original_filename

    file_upload(printer_params[:photo])

    @printer = Printer.new(
      :title => printer_params[:title],
      :description => printer_params[:description],
      :cartrige_id => printer_params[:cartrige_id],
      :photo => printer_params[:photo].original_filename)

    if @printer.save
      redirect_to @printer
    else
      render "new"
    end
  end

  def update
    @printer = Printer.find(params[:id])
    file_remove(@printer.photo)
    printer_params[:photo].original_filename = "#{Time.now.to_i}" << printer_params[:photo].original_filename
    file_upload(printer_params[:photo])

    if @printer.update(
      :title => printer_params[:title],
      :description => printer_params[:description],
      :cartrige_id => printer_params[:cartrige_id],
      :photo => printer_params[:photo].original_filename)
      redirect_to @printer
    else
      render "edit"
    end
  end

  def destroy
    @printer = Printer.find(params[:id])
    file_remove(@printer.photo)

    @printer.destroy
    redirect_to printers_path
  end

  private
  def printer_params
    params.require(:printer).permit(:title,:description,:cartrige_id,:photo)
  end

  def file_remove(file_name)
    File.delete(Rails.root.join('app','assets','images','printers',
       file_name)) if File.exist?(Rails.root.join('app','assets','images','printers',
          file_name))
  end

  def file_upload(file)
    File.open(Rails.root.join('app','assets','images','printers',
       file.original_filename), 'wb') do |f|
       f.write(file.read)
    end
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  def index
    @cartriges = Cartrige.all
    

  end

  def new
  end

  def show
  end

  def edit
  end

  def cartrige_printers(cartrige_id)
    Printer.where(cartrige_id: "#{cartrige_id}").all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartrige_helper.rb
module CartrigeHelper
end

app/helpers/cartriges_helper.rb
module CartrigesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/printer_helper.rb
module PrinterHelper
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/cartriges/_form.html.erb
<%= form_with model: @cartrige,enctype: "multipart/form-data" ,local: true do | form | %>
<div>
  <p>
    <%= form.label :title, "Название" %>
    <br>
    <%= form.text_field :title %>
  </p>
  <% if @cartrige.errors[:title].any?  %>
    <p class='error-hints'>
      <ul>
        <% @cartrige.errors[:title].each do | m | %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
</div>
<div>
  <p>
    <%= form.label :description, "Описание" %>
    <br>
    <%= form.text_area :description %>
  </p>
  <% if @cartrige.errors[:description].any?  %>
    <p class='error-hints'>
      <ul>
        <% @cartrige.errors[:description].each do | m | %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
</div>
<div>
  <p>
    <%= form.label :color, "Цвет" %>
    <br>
    <%= form.text_field :color %>
  </p>
  <% if @cartrige.errors[:color].any?  %>
    <p class='error-hints'>
      <ul>
        <% @cartrige.errors[:color].each do | m | %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
</div>
<div>
  <p>
    <%= form.label :resource, "Ресурс" %>
    <br>
    <%= form.number_field :resource %>
  </p>
  <% if @cartrige.errors[:resource].any?  %>
    <p class='error-hints'>
      <ul>
        <% @cartrige.errors[:resource].each do | m | %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
</div>
<div>
  <p>
    <%= form.label :photo, "Изображение" %>
    <br>
    <%= form.file_field :photo %>
  </p>
</div>
<div>
  <p>
    <%= form.submit "Сохранить" %>
  </p>
</div>
<% end %>

app/views/cartriges/edit.html.erb
<%= render "form" %>
<p><%= link_to "Назад к списку", cartriges_path %></p>

app/views/cartriges/index.html.erb
<h1>Все картриджи</h1>
<p><%= link_to "Добавить картридж", new_cartrige_path %></p>
<div class="d-flex h-list-start wrap width-1400 center">
  <% @cartriges.each do | cartrige | %>
    <div class="list-item">
      <div class="list-item_img">
        <%= image_tag("cartriges/#{cartrige.photo}") %>
      </div>
      <div>
        <p>
          <strong>Название:</strong>
          <%= cartrige.title %>
          <br>

        </p>
      </div>
      <div>
        <%= link_to "Подробнее", cartrige_path(cartrige) %>
        <%= link_to "Изменить", edit_cartrige_path(cartrige) %>
        <%= link_to "Удалить", cartrige_path(cartrige), method: :delete, data: { confirm: 'Вы уверены?' } %>
      </div>
    </div>

  <% end %>
</div>

app/views/cartriges/new.html.erb
<%= render "form" %>
<p><%= link_to "Назад к списку", cartriges_path %></p>

app/views/cartriges/show.html.erb
<h1><%= @cartrige.title %></h1>
<p><%= @cartrige.description %></p>
<p>Характеристики:</p>
<ol>
  <li>Цвет: <%= @cartrige.color %></li>
  <li>Количество использований: <%= @cartrige.resource %> страниц</li>
</ol>
<div class="list-item_img"><%= image_tag("cartriges/#{@cartrige.photo}") %></div>
<hr>
<p>Подходит к принтерам:</p>
<% @cartrige.printers.each do |p| %>
<div>
<p><%=link_to p.title, "/printers/#{p.id}"%></p>

</div>
<% end %>

<p><%= link_to "Назад к списку", cartriges_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HpCartriges</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <div class="logo text-center"><%= link_to "HP LaserJet справочник", root_path %></div>
      </div>
    </header>
    <main class="d-flex h-list-around stretch">
      <div class="container nav p-5">
        <p><strong>Навигация:</strong></p>
        <p><%= link_to "Принтеры", printers_path %></p>
        <p><%= link_to "Картриджи", cartriges_path %></p>
        <p><%= link_to "Таблица совместимостей", controller: :trees %></p>

      </div>
      <div class=" container content grow-4 p-5 max-width">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/main/index.html.erb
<h1>Добро пожаловать!</h1>

<div>
  <p>Данный справочник позволяет:</p>
  <ul>
    <li>Просматривать принтеры и картриджи</li>
    <li>Узнать какой картридж нужен для определенной модели принтера</li>
    <li>Редактировать список картриджей и принтеров</li>
  </ul>
</div>

<!-- TODO: сделать дерево принтеров->картриджей -->

app/views/printers/_form.html.erb
<%= form_with model: @printer, local: true do | form | %>
<div>
  <p>
    <%= form.label :title, "Модель" %>
    <br>
    <%= form.text_field :title %>
  </p>
    <% if @printer.errors[:title].any? %>
       <p class="error-hints">
         <ul>
           <% @printer.errors[:title].each do | m | %>
           <li><%= m %></li>
           <% end %>
         </ul>
       </p>
    <% end %>
</div>
<div>
  <p>
    <%= form.label :description, "Описание" %>
    <br>
    <%= form.text_area :description %>
  </p>
  <% if @printer.errors[:description].any? %>
  <p class="error-hints">
    <ul>
      <% @printer.errors[:description].each do | m | %>
      <li><%= m %></li>
      <% end %>
    </ul>
  </p>
  <% end %>
</div>
<div>
  <p>
    <%= form.label :cartrige_id, "Картридж" %>
    <br>

  <%= form.collection_select("cartrige_id",Cartrige.all,:id,:title, prompt: "Нет картриджа") %>
  </p>
  <% if @printer.errors[:cartrige_id ].any? %>
  <p class="error-hints">
    <ul>
      <% @printer.errors[:cartrige_id].each do | m | %>
      <li><%= m %></li>
      <% end %>
    </ul>
  </p>
  <% end %>
</div>
<div>
  <p>
    <%= form.label :photo, "Изображение" %>
    <br>
    <%= form.file_field :photo %>
  </p>
</div>
<div>
  <p>
    <%= form.submit "Сохранить" %>
  <p>
</div>
<% end %>

app/views/printers/edit.html.erb
<%= render "form" %>
<p><%= link_to "Назад к списку", printers_path %></p>

app/views/printers/index.html.erb
<h1>Все принтеры</h1>
<p><%= link_to "Добавить принтер", new_printer_path %></p>

  <div class="d-flex h-list-start wrap width-1400 center">
    <% @printers.each do | printer | %>
      <div class="list-item">
        <div class="list-item_img">
          <%= image_tag("printers/#{printer.photo}") %>
        </div>
        <div>
          <p>
            <strong>Название:</strong>
            <%= printer.title %>
          </p>
        </div>
        <div>
          <%= link_to "Подробнее", printer_path(printer) %>
          <%= link_to "Изменить", edit_printer_path(printer) %>
          <%= link_to "Удалить", printer_path(printer), method: :delete, data: { confirm: 'Вы уверены?' } %>
        </div>
      </div>

    <% end %>
  </div>

app/views/printers/new.html.erb
<%= render "form" %>
<p><%= link_to "Назад к списку", printers_path %></p>

app/views/printers/show.html.erb
<h1><%= @printer.title %></h1>
<p><%= @printer.description %></p>
<div class="list-item_img"><%= image_tag("printers/#{@printer.photo}") %></div>
<p>Совместимый картридж: <%= @printer.cartrige.title %></p>


<p><%= link_to "Назад к списку", printers_path %></p>

app/views/trees/edit.html.erb
<h1>Trees#edit</h1>
<p>Find me in app/views/trees/edit.html.erb</p>

app/views/trees/index.html.erb
<h2>Таблица совместимостей</h2>

<div>
  <table>
    <tr>
      <th>Картриджи</th>
      <th>Принтеры</th>
    </tr>
    <% @cartriges.each do |c| %>
      <tr>
        <td><%= link_to c.title, cartrige_path(c) %></td>
        <td>
          <ul>
            <% @curr_printers = Printer.where(cartrige_id: "#{c.id}").all
          @curr_printers.each do |p| %>
              <li><%= link_to p.title, printer_path(p) %></li>
            <% end %>
          </ul>

        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/trees/new.html.erb
<h1>Trees#new</h1>
<p>Find me in app/views/trees/new.html.erb</p>

app/views/trees/show.html.erb
<h1>Trees#show</h1>
<p>Find me in app/views/trees/show.html.erb</p>